FROM rust:1.86.0-slim AS builder

WORKDIR /app
COPY . .

RUN cargo build --release
EXPOSE 8080

# prod stage, get rid of unnecessary compilation files
FROM gcr.io/distroless/cc
COPY --from=builder /app/target/release/actix-backend /
CMD ["./actix-backend"]
